# Generated by Django 6.0.6 on 2026-06-09 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventReplayJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('event_version', models.CharField(blank=True, help_text='Specific version or all', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('events_processed', models.PositiveIntegerField(default=0)),
                ('events_failed', models.PositiveIntegerField(default=0)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('triggered_by', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event Replay Job',
                'verbose_name_plural': 'Event Replay Jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('event_version', models.CharField(default='v1', help_text='e.g. v1, v2', max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('schema_validated', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, help_text='Service or app that produced the event', max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('causation_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Event Store',
                'verbose_name_plural': 'Event Store',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='events_even_event_t_c1c780_idx'), models.Index(fields=['event_version'], name='events_even_event_v_9bea74_idx'), models.Index(fields=['correlation_id'], name='events_even_correla_f0c776_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscriber_name', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('last_event_id', models.CharField(blank=True, max_length=255)),
                ('last_processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event Subscription',
                'verbose_name_plural': 'Event Subscriptions',
                'unique_together': {('subscriber_name', 'event_type')},
            },
        ),
    ]
