# Generated by Django 6.0.5 on 2026-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_circuitbreaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitbreaker',
            name='half_open_requests_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='is_half_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
