# Generated by Django 6.0.5 on 2026-06-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_circuitbreaker_half_open_requests_made_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circuitbreaker',
            name='is_half_open',
        ),
        migrations.RemoveField(
            model_name='circuitbreaker',
            name='is_open',
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('half_open', 'Half Open')], default='closed', max_length=20),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
