# Generated by Django 6.0.6 on 2026-06-09 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workflows', '0008_workflowtemplate_node_position_x_node_position_y_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of template variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('twilio', 'Twilio'), ('whatsapp', 'WhatsApp'), ('hubspot', 'HubSpot'), ('salesforce', 'Salesforce'), ('gmail', 'Gmail'), ('google_sheets', 'Google Sheets'), ('google_drive', 'Google Drive'), ('slack', 'Slack'), ('discord', 'Discord'), ('generic_webhook', 'Generic Webhook'), ('custom', 'Custom')], max_length=50)),
                ('category', models.CharField(choices=[('email', 'Email'), ('messaging', 'Messaging'), ('crm', 'CRM'), ('google', 'Google'), ('slack', 'Slack / Discord'), ('webhook', 'Webhook'), ('storage', 'Storage'), ('other', 'Other')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('sendgrid', 'SendGrid'), ('mailgun', 'Mailgun'), ('smtp', 'Custom SMTP'), ('ses', 'Amazon SES')], max_length=20)),
                ('api_key', models.TextField(blank=True, help_text='Encrypted API key')),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('daily_limit', models.PositiveIntegerField(default=1000)),
                ('daily_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_providers', to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credentials', models.JSONField(default=dict, help_text='Encrypted connection credentials')),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('test_status', models.CharField(blank=True, max_length=20)),
                ('test_error', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='MessagingProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('twilio_sms', 'Twilio SMS'), ('twilio_whatsapp', 'Twilio WhatsApp'), ('slack', 'Slack'), ('discord', 'Discord'), ('telegram', 'Telegram')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('phone_number', models.CharField(blank=True, help_text='For SMS/WhatsApp', max_length=50)),
                ('webhook_url', models.URLField(blank=True, help_text='For Slack/Discord incoming webhooks')),
                ('channel_id', models.CharField(blank=True, help_text='Slack channel or Discord channel ID', max_length=255)),
                ('bot_token', models.TextField(blank=True, help_text='Encrypted bot token')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_providers', to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField(help_text='Encrypted access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted refresh token')),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('scope', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_tokens', to='integrations.integration')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url_path', models.CharField(help_text='Unique path for the webhook URL', max_length=255, unique=True)),
                ('secret', models.CharField(blank=True, help_text='Secret for signature verification', max_length=255)),
                ('provider', models.CharField(default='generic', help_text='e.g., github, stripe, generic', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('total_received', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='accounts.organization')),
                ('trigger_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_triggers', to='workflows.workflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headers', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_deliveries', to='workflows.workflowexecution')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'verbose_name': 'Webhook Delivery',
                'verbose_name_plural': 'Webhook Deliveries',
                'ordering': ('-received_at',),
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['provider', 'is_active'], name='integration_provide_587cda_idx'),
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['category'], name='integration_categor_6c4bea_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['url_path'], name='integration_url_pat_b50b67_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['provider'], name='integration_provide_6e0a28_idx'),
        ),
    ]
