# Generated by Django 6.0.6 on 2026-06-09 03:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workflows', '0008_workflowtemplate_node_position_x_node_position_y_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('component', models.CharField(choices=[('redis', 'Redis'), ('database', 'Database'), ('celery', 'Celery'), ('celery_beat', 'Celery Beat'), ('channels', 'Channels'), ('cache', 'Cache'), ('storage', 'Storage')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('unhealthy', 'Unhealthy')], max_length=20)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health Checks',
                'ordering': ('-checked_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(choices=[('workflow_failed', 'Workflow Failed'), ('workflow_slow', 'Workflow Slow Execution'), ('node_failed', 'Node Failed'), ('circuit_open', 'Circuit Breaker Open'), ('integration_error', 'Integration Error'), ('execution_failure_rate', 'Execution Failure Rate'), ('queue_depth', 'Queue Depth'), ('worker_cpu', 'Worker CPU Usage'), ('memory_usage', 'Memory Usage')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('condition_operator', models.CharField(default='>', help_text='>, <, ==, >=, <=', max_length=10)),
                ('condition_value', models.FloatField(help_text='Threshold value that triggers the alert')),
                ('cooldown_minutes', models.PositiveIntegerField(default=15, help_text='Minimum time between alerts')),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='accounts.organization')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('discord', 'Discord'), ('webhook', 'Webhook'), ('sms', 'SMS')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Channel-specific configuration (webhook URL, email, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_channels', to='accounts.organization')),
                ('rules', models.ManyToManyField(blank=True, related_name='channels', to='monitoring.alertrule')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='firing', max_length=20)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.alertchannel')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.alertrule')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='monitoring__status_4b15ca_idx'), models.Index(fields=['rule', '-created_at'], name='monitoring__rule_id_706ea6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('running_workflows', 'Running Workflows'), ('failed_workflows', 'Failed Workflows'), ('completed_workflows', 'Completed Workflows'), ('success_rate', 'Success Rate'), ('avg_duration_ms', 'Average Duration (ms)'), ('total_executions', 'Total Executions'), ('active_nodes', 'Active Nodes'), ('queue_depth', 'Queue Depth'), ('worker_count', 'Worker Count')], db_index=True, max_length=50)),
                ('metric_value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Dashboard Metric',
                'verbose_name_plural': 'Dashboard Metrics',
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['metric_type', '-recorded_at'], name='monitoring__metric__bb25a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('steps_snapshot', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_history', to='accounts.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_history', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Execution History',
                'verbose_name_plural': 'Execution Histories',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['workflow', '-started_at'], name='monitoring__workflo_1f04a2_idx'), models.Index(fields=['status', '-started_at'], name='monitoring__status_94924b_idx'), models.Index(fields=['-started_at'], name='monitoring__started_f4bbe4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('cpu_time_ms', models.IntegerField(blank=True, null=True)),
                ('memory_usage_mb', models.FloatField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(db_index=True, max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='workflows.workflowexecution')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_metrics', to='accounts.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_metrics', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Execution Metric',
                'verbose_name_plural': 'Execution Metrics',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['workflow', '-started_at'], name='monitoring__workflo_753316_idx'), models.Index(fields=['status', '-started_at'], name='monitoring__status_234199_idx'), models.Index(fields=['-started_at'], name='monitoring__started_1be0c5_idx')],
            },
        ),
    ]
