# Generated by Django 6.0.5 on 2026-05-27 03:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='next_node',
        ),
        migrations.AlterField(
            model_name='node',
            name='configuration',
            field=models.JSONField(blank=True, db_index=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('trigger', 'Trigger'), ('condition', 'Condition'), ('email', 'Email'), ('webhook', 'Webhook'), ('delay', 'Delay'), ('event_trigger', 'Event Trigger'), ('schedule_trigger', 'Schedule Trigger')], max_length=20),
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='workflows.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='workflows.node')),
            ],
        ),
    ]
