# Generated by Django 6.0.5 on 2026-05-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_remove_node_next_node_alter_node_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconnection',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
