# Generated by Django 6.0.5 on 2026-05-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_nodeconnection_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconnection',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
