# Generated by Django 6.0.5 on 2026-06-02 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_executionstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='compensation_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensates', to='workflows.node'),
        ),
    ]
