# Generated by Django 6.0.5 on 2026-06-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_node_compensation_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowexecution',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
